---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: template
  namespace: observemicroprofile

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: template
  namespace: observemicroprofile
spec:
  failedBuildsHistoryLimit: 1
  successfulBuildsHistoryLimit: 1
  output:
    to:
      kind: ImageStreamTag
      name: template:latest
  source:
    type: Git
    git:
      uri: https://github.com/codelair-io/observemicroprofile.git
    contextDir: template
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker

---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: template
  namespace: observemicroprofile
spec:
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - template
        from:
          kind: ImageStreamTag
          name: template:latest
      type: ImageChange
  selector:
    app: template
  replicas: 1
  template:
    metadata:
      labels:
        app: template
    spec:
      containers:
        - name: template
          image: ""
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: template
  namespace: observemicroprofile
spec:
  selector:
    app: template
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: template
  namespace: observemicroprofile
spec:
  selector:
    matchLabels:
      app: template
  endpoints:
    - path: /metrics
      scheme: http
      targetPort: 8080

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: template
  namespace: observemicroprofile
spec:
  path: /api
  to:
    kind: Service
    name: template
  port:
    targetPort: 8080
