kumuluzee:
  opentracing:
    jaeger:
      service-name: KumuluzEE project # if not set kumuluzee.name value is used
      agent-host: otel-agent.obs.svc.cluster.local # default agent host
      agent-port: 14268 # default agent port
      #endpoint: /api/traces
#      propagation: jaeger
      traceid-128bit: true
  logs:
    loggers:
      - name: ''
        level: DEBUG
